DataBiosphere/terra-test-runner

- src/main/java/bio/terra/testrunner/runner/TestRunner.java
- src/main/java/bio/terra/testrunner/runner/config/ServerSpecification.java
Just a minor fix so GH action can run both resiliency tests and other test types.
Additional notes: The main purpose of this PR is to enable different types of tests (Integration / Resiliency) to use the same test configuration file. The assumption is that Integration tests do not need the `KubernetesClientUtils` to manipulate a cluster. So if developers have only integration tests in mind, the test config specification they create might not have the cluster specification and test runner validation will fail. If the assumption wasn't correct (as Mariko points out) then we need to figure out what would be the best way to use one test configuration for all test types.
Added @gjuggler to this Pull Request. Since Mariko is on vacation, I would like Dan and Greg to review and give this ticket …
> QA-1422: Updated TestRunner validation to check cluster specification.

- src/main/java/bio/terra/testrunner/common/utils/KubernetesClientUtils.java
- src/main/java/bio/terra/testrunner/runner/TestRunner.java
- src/main/java/bio/terra/testrunner/runner/config/ServerSpecification.java
- testrunner-k8s-role.yml.template
The goal of this Pull Request is for the extension of the current Test Runner Framework to import `MCTerra` Component versions from the target Kubernetes namespace.
The ground truth of the component versions for different environments are obtained from the `terra-helmfile` version manifests.
In order to support the `ConfigMap` operations the Test Runner Library needs, the RBAC role has also been updated to enable `get, patch, and update` operations pertaining to the Component Version ConfigMap.
> QA-1438: Extend Test Runner Framework to support MCTerra Component Version ConfigMap.

- build.gradle
- src/main/java/bio/terra/testrunner/collector/MeasurementCollectionScript.java
- src/main/java/bio/terra/testrunner/common/commands/PrintHelp.java
- src/main/java/bio/terra/testrunner/runner/TestRunner.java
- src/main/java/bio/terra/testrunner/runner/TestScriptResult.java
- src/main/java/bio/terra/testrunner/uploader/ResultUploader.java
- src/main/java/scripts/uploadscripts/CompressDirectoryToBucket.java
- src/main/java/scripts/uploadscripts/SummariesToBigQuery.java
One bug fix for upload scripts that is showing up in WSM + a few other less urgent bugs/requested changes.
- ([PF-790](https://broadworkbench.atlassian.net/browse/PF-790)) Included the test script name and description in the result summary. Previously only the description was included, and this was causing an error when uploading results to BQ. 
- More detail: The test script description (different from the test configuration description) is generated by Test Runner as test script class name + list of parameters. The upload script was trying to lookup a test script result by name and failing when there were any parameters, because then name != description.
- Moved the two upload scripts (copy results into a GCS bucket, insert results into a BQ dataset) into the Test Runner library. These …
> PF-790, PF-791, PF-779, PF-443: Move upload scripts into Test Runner library + bug fixes.

- .gitignore
- README.md
- build.gradle
- src/main/java/bio/terra/testrunner/common/utils/AuthenticationUtils.java
- src/main/java/bio/terra/testrunner/common/utils/KubernetesClientUtils.java
- src/main/java/bio/terra/testrunner/runner/TestRunner.java
- src/main/java/bio/terra/testrunner/runner/config/ApplicationSpecification.java
- src/main/java/bio/terra/testrunner/runner/config/ClusterSpecification.java
- src/main/java/bio/terra/testrunner/runner/config/KubernetesSpecification.java
- src/main/java/bio/terra/testrunner/runner/config/TestConfiguration.java
This PR serves the following purpose.
Avoids caching the service accounts for obtaining test runner, user delegated access tokens (see [PF-657](https://broadworkbench.atlassian.net/browse/PF-657)).
Skip modification of Kubernetes if the application component label used to identify a Kubernetes deployment does not exist.
Updated `.gitignore` to ignore local helm files.
Refactored application specification so that the `componentLabel` and `apiComponetLabel` properties are now part of Cluster Specification. These properties can now be configured at the Server Specification and applied to all test configs. These labels are Terraformed and rarely change so it makes sense to move them into Server Spec rather than replicating them in every test config.
Bump version to `0.0.5-SNAPSHOT`.
> PF-657: Removed the caching of service accounts for obtaining various credentials for running tests.

- build.gradle
- src/main/java/bio/terra/testrunner/common/utils/KubernetesClientUtils.java
This PR is to tighten up the definition of pod readiness by ensuring ALL containers within a pod are ready.
The fix addresses occasional NPE while waiting for pod to recover during resiliency tests.
> QA-1504: Enhanced logic of getApiReadyPods to fix NPE

- build.gradle
- src/main/java/bio/terra/testrunner/runner/TestRunner.java
- src/main/java/bio/terra/testrunner/runner/TestScriptResult.java
- src/main/java/bio/terra/testrunner/runner/UserJourneyResult.java
- Previously Test Runner was serializing any exceptions thrown by a user journey threads. Test Runner doesn't need to be serializing the exception object. It just needs to preserve the stack trace and message for debugging test failures. This PR changes Test Runner to no longer serialize the full exception object, just the stack trace and message.
- Fixed a bug where Test Runner was not handling `Error`s, only `Exception`s.
**TODO**: Change the version to `0.0.7` and publish before merging this. It's already published as `0.0.7a` for testing in other repos.
> PF-861: Serialize exception stack trace as string, instead of full object.

- build.gradle
- src/main/java/bio/terra/testrunner/runner/config/ServerSpecification.java
- tools/component-version-configmap.yml.template
This is a minor update to support `Policy Team's` new service endpoint `policyManagerUri`. The Jira ticket is [QA-1554](https://broadworkbench.atlassian.net/browse/QA-1554).
Added `policyManagerUri` to `ServerSpecification`. 
The uri properties are already optional, validation does not check for null or empty values so we should be fine.
> QA-1554: Update TestRunner with new policyManagerUri property in ServerSpecification

- build.gradle
- src/main/java/bio/terra/testrunner/runner/TestRunner.java
- src/main/java/bio/terra/testrunner/runner/config/TestConfiguration.java
This PR enhances `TestRunner` to include the test configuration file name from `TestSuite` as a new property (`resourceFileName` property) in `TestRunSummary` and `TestConfiguration` classes.
The `resourceFileName` property is of the format
- `perf/**.json`
- `integration/**.json`
- `resiliency/**.json`
etc.
This enhancement facilitates grouping of test runner results on the dashboard.
For a screen shot of the `BigQuery` table with the new `resourceFileName` property, see the Acceptance Criteria section of the Jira ticket [QA-1607.](https://broadworkbench.atlassian.net/browse/QA-1607).
For a trial WSM test run using this new version (`0.0.9-SNAPSHOT`), please refer to workflow [https://github.com/DataBiosphere/terra-workspace-manager/runs/3956951516?check_suite_focus=true](https://github.c …
> QA-1607: Enhance TestRunner to include test types based on the test suite configuration.

- src/main/java/scripts/versionscripts/model/HelmRelease.java
The helm file has a cluster property for `alpha` environment (see [https://github.com/broadinstitute/terra-helmfile/blob/master/environments/live/alpha.yaml](https://github.com/broadinstitute/terra-helmfile/blob/master/environments/live/alpha.yaml)). 
Added optional `cluster` property to `HelmVersion` and `defaultCluster` property to `HelmRelease` models.
> Added optional properties defaultCluster, cluster.

- build.gradle
Force transitive log4j api and slf4j library dependencies to the latest version due to security concerns. We do not use log4j core, so nothing to update there.
> [PF-1246] Force update transitive log4j dependencies

- build.gradle
Bump log4j-api transitive dependency version from 2.15.0 to 2.16.0.
> [PF-1251] Bump log4j api to 2.16.0

- build.gradle
Update log4j-api and log4j-to-slf4j dependencies to version 2.17. This service does not use log4j-core.
> [PF-1260] Log4j version to 2.17

- README.md
- build.gradle
- src/main/java/bio/terra/testrunner/collector/MeasurementCollectionScript.java
- src/main/java/bio/terra/testrunner/collector/MeasurementCollector.java
- src/main/java/bio/terra/testrunner/collector/config/MeasurementCollectionScriptSpecification.java
- src/main/java/bio/terra/testrunner/common/utils/LogsUtils.java
- src/main/java/bio/terra/testrunner/runner/DeploymentScript.java
- src/main/java/bio/terra/testrunner/runner/DisruptiveScript.java
- src/main/java/bio/terra/testrunner/runner/TestRunner.java
- src/main/java/bio/terra/testrunner/runner/TestScript.java
- src/main/java/bio/terra/testrunner/runner/VersionScript.java
- src/main/java/bio/terra/testrunner/runner/config/DeploymentScriptSpecification.java
- src/main/java/bio/terra/testrunner/runner/config/DisruptiveScriptSpecification.java
- src/main/java/bio/terra/testrunner/runner/config/ServerSpecification.java
- src/main/java/bio/terra/testrunner/runner/config/TestScriptSpecification.java
- src/main/java/bio/terra/testrunner/runner/config/VersionScriptSpecification.java
- src/main/java/bio/terra/testrunner/uploader/ResultUploader.java
- src/main/java/bio/terra/testrunner/uploader/UploadScript.java
- src/main/java/bio/terra/testrunner/uploader/config/UploadScriptSpecification.java
- src/main/java/scripts/uploadscripts/CompressDirectoryToBucket.java
- src/main/java/scripts/uploadscripts/SummariesToBigQuery.java
- src/main/java/scripts/versionscripts/ReadFromGitCommitLog.java
- src/main/java/scripts/versionscripts/ReadFromTerraHelmfileRepo.java
Renamed all instances of `parameters` to `parametersMap` and set the new `parametersMap` access to WRITE_ONLY to expose it to scripts using `TestRunner`. The original `parameters` properties are now READ_ONLY and will be used for solely for interfacing with test reporting.
Bump version to 0.1.3-SNAPSHOT.
> Renamed all instances of parameters to parametersMap 

- build.gradle
- src/main/java/bio/terra/testrunner/runner/config/ServerSpecification.java
This switches the last place this library uses the Apache Commons Lang 2 library to 3 (several other classes here already use `org.apache.commons.lang3`). I've also added this as a direct dependency since we use it directly.
The existing setup implicitly requires both Apache Commons lang 2 and 3, this broke RBS's client test project when it stopped (transitively) pulling in commons lang 2.
> [PF-1531] Switch to apache lang3, add explicit dependency

- src/main/java/bio/terra/testrunner/runner/config/ServerSpecification.java
The catalog service depends on the Rawls service (https://github.com/broadinstitute/rawls) and needs a configurable property in `ServerSpecification` to write integration tests against this service.
> DC-345: Add server configuration property for the rawls service

- README.md
- build.gradle
- src/main/java/bio/terra/testrunner/runner/RetryLogic.java
- src/main/java/bio/terra/testrunner/runner/TestRunner.java
- src/main/java/bio/terra/testrunner/runner/UserJourneyResult.java
- src/main/java/bio/terra/testrunner/runner/config/TestConfiguration.java
**Summary**
Provide a way to automatically retry a testrunner test on a failed run. The `TestConfiguration` accepts two new properties: `maxRetries`, `timeToWait` with default values 3 and 2000ms, respectively.
**Context & Background**
Tests have been failing flakily when using SAM dev, due to a connection timeout error. The errors are inside services our tests call, not in calls to SAM directly, and in some cases occur inside flights, so it's hard to add retries within the test to fix this. 
This ticket is to provide a retry configuration. Each test script thread will continue to run a specified number of times on error according to the new configuration. 
**A/C**
Test runner framework will retry a test when error occurs and record the number of retries.
> QA-1914: Enable a test script to retry a number of times through configuration.

- wiki/home.md
- wiki/quickstart.md
The Wiki page (first draft) is now up. 
[https://github.com/DataBiosphere/terra-test-runner/wiki](https://github.com/DataBiosphere/terra-test-runner/wiki)
The [Quick Start ](https://github.com/DataBiosphere/terra-test-runner/wiki/Quick-Start) page in this draft shows how to integrate `Test Runner Framework` with `Scala` repo, complete with examples of porting existing `swat` tests into `Test Runner`. 
There are several `Gradle` repos already using `Test Runner` that provide great examples so it's less of a priority to write a formal Wiki for `Gradle` in this first draft.
`Maven` section will be added when we have time.
> QA-1952: Make Wiki page for test runner framework.

- .github/workflows/push.yml
The `joschi/setup-jdk@v2` Github action is deprecated and the recommendation is to move to the official github setup-java action with the `temurin` distribution: see https://github.com/joschi/setup-jdk#-notice
> [PF-1731] Replace Java setup action

- build.gradle
- src/main/java/bio/terra/testrunner/common/utils/KubernetesClientUtils.java
- src/main/java/bio/terra/testrunner/runner/UserJourneyResult.java
The Kubernetes Client version has not been updated for a while. This PR updates the client version to match release 1.24. This will resolve issues for any tests that depends on release 1.24 environment.
> Update Kubernetes Client API version to match release 1.24.

- tools/publish.sh
Add support for M1 Macs (arm64) in artifact publish script
Changes were tested with local run
```
BUILD SUCCESSFUL in 5s
12 actionable tasks: 12 executed
[pool-4-thread-1] Deploying artifact: https://broadinstitute.jfrog.io/broadinstitute/libs-snapshot-local/bio/terra/terra-test-runner/0.1.8-SNAPSHOT/terra-test-runner-0.1.8-SNAPSHOT.jar
[pool-4-thread-1] Deploying artifact: https://broadinstitute.jfrog.io/broadinstitute/libs-snapshot-local/bio/terra/terra-test-runner/0.1.8-SNAPSHOT/terra-test-runner-0.1.8-SNAPSHOT.module
[pool-4-thread-1] Deploying artifact: https://broadinstitute.jfrog.io/broadinstitute/libs-snapshot-local/bio/terra/terra-test-runner/0.1.8-SNAPSHOT/terra-test-runner-0.1.8-SNAPSHOT.pom
> Task :artifactoryDeploy
Deploying build info...
Build-info successfully deployed. …
```
> [PF-1545] Add support for M1 Macs (arm64) in artifact publish script

- .github/workflows/push.yml
Replace deprecated commands in GH actions & workflows.
- use actions/setup-java@v3 instead of v2
- use actions/checkout@v3 instead of v2
- use actions/cache@v3 instead of v2
- use actions/upload-artifact@v3 instead of v2
- use setup-node@v3 instead of v2
- replace 'set-output' command
> [TERRA-434] Replace deprecated commands in GH actions & workflows
